import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";

const RubikFont = Rubik({
  subsets: ["latin"],
  variable: '--rubik-font'
})

export const metadata: Metadata = {
  title: "Lovenly - Crie memórias",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="[&::-webkit-scrollbar]:w-2
  [&::-webkit-scrollbar-track]:bg-zinc-200
  [&::-webkit-scrollbar-thumb]:bg-zinc-300 [&::-webkit-scrollbar-thumb]:rounded-full" lang="pt-br">
      <head>
        <link rel="icon" type="image/png" href="./logo.png" />
      </head>
      <body
        className={`${RubikFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
